AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - com.shufan::wearable-servlerless
Resources:
  WearableLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.shufan.wearable.LambdaFunctionHandler::handleRequest
      Runtime: java8
      CodeUri: target/wearable-1.0.0.jar
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  WearableLambdaApi11271210:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: WearableLambdaApi11271210
